
时间：2016-12-27 19:56:53,520 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：703057 
System.Exception: {"fg":"1","x":"13426","y":"7021","l":"14"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 19:56:53,520 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：703057 
System.Exception: {"fg":"3","x":"13426","y":"7019","l":"14"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 19:56:54,183 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：703721 
System.Exception: {"fg":"1","x":"13428","y":"7020","l":"14"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 19:57:45,246 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：754783 
System.Exception: {"fg":"3","x":"26804","y":"13965","l":"15"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 19:57:45,246 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：754783 
System.Exception: {"fg":"5","x":"26804","y":"13963","l":"15"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:06:38,427 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：1287965 
System.Exception: {"fg":"3","x":"3362","y":"1734","l":"12"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:07:18,005 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：1327542 
System.Exception: {"fg":"2","x":"1693","y":"837","l":"11"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:07:18,819 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：1328357 
System.Exception: {"fg":"2","x":"1695","y":"839","l":"11"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:07:19,630 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：1329168 
System.Exception: {"fg":"2","x":"1693","y":"840","l":"11"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:08:23,410 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：1392948 
System.Exception: {"fg":"3","x":"13426","y":"7019","l":"14"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:24:26,503 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2356040 
System.Exception: {"fg":"5","x":"6716","y":"3514","l":"13"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:24:27,002 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2356540 
System.Exception: {"fg":"4","x":"6723","y":"3510","l":"13"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:29:17,099 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2646636 
System.Exception: {"fg":"6","x":"419","y":"216","l":"9"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:29:26,856 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2656394 
System.Exception: {"fg":"6","x":"107","y":"54","l":"7"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:29:36,913 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2666451 
System.Exception: {"fg":"1","x":"1678","y":"877","l":"11"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:30:42,336 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2731874 
System.Exception: {"fg":"4","x":"53741","y":"28091","l":"16"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:30:59,320 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2748858 
System.Exception: {"fg":"4","x":"107483","y":"56183","l":"17"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-27 20:33:06,732 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：2876269 
System.Exception: {"fg":"2","x":"835","y":"435","l":"10"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---
