
时间：2017-01-04 21:19:58,745 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6537715 
System.Exception: {"fg":"4","x":"11","y":"5","l":"4"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-04 21:19:59,390 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6538360 
System.Exception: {"fg":"2","x":"11","y":"4","l":"4"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-04 21:25:17,565 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6856536 
System.Exception: {"fg":"1","x":"53320","y":"27409","l":"16"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-04 21:25:41,940 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6880910 
System.Exception: {"fg":"4","x":"211","y":"97","l":"8"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-04 21:35:30,434 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：7469404 
System.Exception: {"fg":"1","x":"12","y":"6","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-04 22:46:49,581 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11748551 
System.Exception: {"fg":"2","x":"11","y":"4","l":"4"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-04 22:46:50,198 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11749168 
System.Exception: {"fg":"6","x":"13","y":"5","l":"4"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---
