
时间：2017-06-15 07:07:34,734 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T找不到服务配置文件)","code":"T找不到服务配置文件"} 
时间：26798675 

时间：2017-06-15 07:23:23,203 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T找不到服务配置文件)","code":"T找不到服务配置文件"} 
时间：27747144 

时间：2017-06-15 07:23:45,859 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T找不到服务配置文件)","code":"T找不到服务配置文件"} 
时间：27769800 

时间：2017-06-15 19:33:25,543 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：650582 
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Convert.ToBase64String(Byte[] inArray, Int32 offset, Int32 length, Base64FormattingOptions options)
   在 System.Convert.ToBase64String(Byte[] inArray)
   在 X.Core.Utility.Secret.ToBase64(String text) 位置 D:\Pro\yt\gis\src\X.Core\Utility\Secret.cs:行号 206
   在 X.App.Apis.sdk._sdk.InitApi() 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\_sdk.cs:行号 23
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\yt\gis\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\yt\gis\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-15 19:33:31,239 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：656278 
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Convert.ToBase64String(Byte[] inArray, Int32 offset, Int32 length, Base64FormattingOptions options)
   在 System.Convert.ToBase64String(Byte[] inArray)
   在 X.Core.Utility.Secret.ToBase64(String text) 位置 D:\Pro\yt\gis\src\X.Core\Utility\Secret.cs:行号 206
   在 X.App.Apis.sdk._sdk.InitApi() 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\_sdk.cs:行号 23
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\yt\gis\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\yt\gis\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-15 19:33:35,710 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：660749 
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Convert.ToBase64String(Byte[] inArray, Int32 offset, Int32 length, Base64FormattingOptions options)
   在 System.Convert.ToBase64String(Byte[] inArray)
   在 X.Core.Utility.Secret.ToBase64(String text) 位置 D:\Pro\yt\gis\src\X.Core\Utility\Secret.cs:行号 206
   在 X.App.Apis.sdk._sdk.InitApi() 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\_sdk.cs:行号 23
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\yt\gis\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\yt\gis\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-15 19:33:40,278 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：665317 
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Convert.ToBase64String(Byte[] inArray, Int32 offset, Int32 length, Base64FormattingOptions options)
   在 System.Convert.ToBase64String(Byte[] inArray)
   在 X.Core.Utility.Secret.ToBase64(String text) 位置 D:\Pro\yt\gis\src\X.Core\Utility\Secret.cs:行号 206
   在 X.App.Apis.sdk._sdk.InitApi() 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\_sdk.cs:行号 23
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\yt\gis\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\yt\gis\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-15 22:25:15,601 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：8263064 
System.IO.IOException: 另一个进程正在使用此文件，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 System.IO.File.Move(String sourceFileName, String destFileName)
   在 X.App.Apis.sdk.svrs.init.getBlocks(String path, x_service s) 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\svrs\init.cs:行号 74
   在 X.App.Apis.sdk.svrs.init.Execute() 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\svrs\init.cs:行号 30
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\yt\gis\src\Web\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\yt\gis\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-15 22:31:28,829 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T服务覆盖失败，错误信息：)","code":"T服务覆盖失败，错误信息："} 
时间：8636292 

时间：2017-06-15 22:31:29,572 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\yt\gis\src\X.Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：8637035 
System.IO.IOException: 另一个进程正在使用此文件，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 System.IO.File.Move(String sourceFileName, String destFileName)
   在 X.App.Apis.sdk.svrs.init.getBlocks(String path, x_service s) 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\svrs\init.cs:行号 74
   在 X.App.Apis.sdk.svrs.init.Execute() 位置 D:\Pro\yt\gis\src\Web\Svr\X.App\Apis\sdk\svrs\init.cs:行号 30
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\yt\gis\src\Web\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\yt\gis\src\Web\X.Web\XApp.cs:行号 31
